using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Invoices.Api.Models
{
    /// <summary>
    /// Invoice Data Transfer Object 
    /// </summary>
    public class InvoiceDto
    {
		/// <summary>
		/// Invoice Number (required)
		/// </summary>
		// chceck for duplicity InvoiceNumber - in Invoicemanager
		public ulong InvoiceNumber { get; set; }
        /// <summary>
        /// Seller's details for thi sinvoice
        /// </summary>
        [JsonPropertyName("seller")]
		public PersonDto? Seller { get; set; } 
        /// <summary>
        /// Buyer's details for this invoice
        /// </summary>
        [JsonPropertyName("buyer")]
		public PersonDto? Buyer { get; set; }
		/// <summary>
		/// date of issue of the invoice yyyy-mm-dd (required)
		/// </summary>
		[DataType(DataType.Date, ErrorMessage = "Invalidní formát datumu. Prosím vyberte z kalendáře nebo zadejte yyyy-mm-dd.")]
		public DateTime Issued { get; set; }
		/// <summary>
		/// due date of the invoice yyyy-mm-dd (required)
		/// </summary>
		[DataType(DataType.Date, ErrorMessage = "Invalidní formát datumu. Prosím vyberte z kalendáře nebo zadjte yyyy-mm-dd.")]
		[CompareDates(nameof(Issued), ErrorMessage = "Datum splatnosti musí být po datumu vystavení")]
		public DateTime DueDate { get; set; }
		/// <summary>
		/// specification what is being invoiced (required)
		/// </summary>
		[StringLength(250, ErrorMessage = "Popis produktu maximálne do 250 znaků.")]
		public string Product { get; set; } = "";
		/// <summary>
		/// final price of the invoice (required)
		/// </summary>
		// validation for possitive number only - in InvoiceManager
		[Range(0.01, double.MaxValue, ErrorMessage = "Cena musí být zadaná jako kladné číslo.")]
		public double Price { get; set; }
		/// <summary>
		/// VAT of the invoice in % (required)
		/// </summary>
		[Range(0, 100, ErrorMessage = "DPH musí být 0-100 (v %).")]
		public int Vat { get; set; }
		/// <summary>
		/// note for the invoice
		/// </summary>
		[StringLength(500, ErrorMessage = "Poznámka maximálne do 500 znaků.")]
		public string Note { get; set; } = "";
		/// <summary>
		/// unique identification key generated by db
		/// </summary>
		[JsonPropertyName("_id")]
		public ulong InvoiceId { get; set; }
    }
}

