using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Invoices.Api.Models
{
    /// <summary>
    /// Invoice Data Transfer Object with validations
    /// </summary>
    public class InvoiceDto
    {
		/// <summary>
		/// Invoice Number (required, validation must be >0)
		/// </summary>
		// chceck for duplicity InvoiceNumber - in Invoicemanager
		[Range(1, double.MaxValue, ErrorMessage = "Číslo faktury musí být zadano jako kladné číslo.")]
		public ulong InvoiceNumber { get; set; }
		/// <summary>
		/// Seller's details for thi sinvoice (validation must be >0)
		/// </summary>
		[JsonPropertyName("seller")]
		public PersonDto? Seller { get; set; }
		/// <summary>
		/// Buyer's details for this invoice (validation must be >0)
		/// </summary>
		[JsonPropertyName("buyer")]
		public PersonDto? Buyer { get; set; }
		/// <summary>
		/// date of issue of the invoice yyyy-mm-dd (required)
		/// </summary>
		[DataType(DataType.Date, ErrorMessage = "Invalidní formát datumu. Prosím zadejte yyyy-mm-dd.")]
		public DateTime Issued { get; set; }
		/// <summary>
		/// due date of the invoice yyyy-mm-dd (required)
		/// </summary>
		[DataType(DataType.Date, ErrorMessage = "Invalidní formát datumu. Prosím zadjte yyyy-mm-dd.")]
		[CompareDates(nameof(Issued), ErrorMessage = "Datum splatnosti musí být po datumu vystavení")]
		public DateTime DueDate { get; set; }
		/// <summary>
		/// specification what is being invoiced (required)
		/// </summary>
		[StringLength(250, MinimumLength = 2, ErrorMessage = "Popis produktu musí mít 2 až 250 znaků.")]
		public string Product { get; set; } = "";
		/// <summary>
		/// final price of the invoice (required)
		/// </summary>
		[Range(0.01, double.MaxValue, ErrorMessage = "Cena musí být zadaná jako kladné číslo.")]
		public double Price { get; set; }
		/// <summary>
		/// VAT of the invoice in % (required)
		/// </summary>
		[Range(0, 100, ErrorMessage = "DPH musí být 0-100 (v %).")]
		public int Vat { get; set; }
		/// <summary>
		/// note for the invoice
		/// </summary>
		[StringLength(200, ErrorMessage = "Poznámka maximálne do 200 znaků.")]
		public string Note { get; set; } = "";
		/// <summary>
		/// unique identification key generated by db
		/// </summary>
		[JsonPropertyName("_id")]
		public ulong InvoiceId { get; set; }
    }
}

