using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Invoices.Data.Models
{
    public class Invoice
    {
        /// <summary>
        /// unique identification key generated by db
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public ulong InvoiceId {  get; set; }
		/// <summary>
		/// Invoice Number (required)
		/// </summary>
		[Required]
		public ulong InvoiceNumber { get; set; }
		/// <summary>
		/// foreign key linking the invoice to the seller (required)
		/// </summary>
		[Required]
		[ForeignKey(nameof(Seller))]
        public ulong? SellerId { get; set; }
        /// <summary>
        /// navigation property to access seller's details, person is seller - issuing the inv.
        /// </summary>
        public virtual Person? Seller { get; set; }
		/// <summary>
		/// foreign key linking the invoice to the buyer (required)
		/// </summary>
		[Required]
		[ForeignKey(nameof(Buyer))]
        public ulong? BuyerId { get; set; }
		/// <summary>
		/// navigation property to access buyer's details, person is buyer - paying the inv.
		/// </summary>
		public virtual Person? Buyer { get; set; }
		/// <summary>
		/// date of issue of the invoice yyyy-mm-dd (required)
		/// </summary>
		[Required]
		public DateTime Issued { get; set; }        // do not use DateOnly, not all frameworks can handle it
		/// <summary>
		/// due date of the invoice yyyy-mm-dd (required)
		/// </summary>
		[Required]
		public DateTime DueDate { get; set; }
		/// <summary>
		/// specification what is being invoiced (required)
		/// </summary>
		[Required]
		public string Product { get; set; } = "";
		/// <summary>
		/// final price of the invoice (required)
		/// </summary>
		[Required]
		public double Price { get; set; }
		/// <summary>
		/// VAT of the invoice in % (required)
		/// </summary>
		[Required]
		public int Vat { get; set; }
        /// <summary>
        /// note for the invoice
        /// </summary>
        public string Note { get; set; } = "";
    }
}
