/*  _____ _______         _                      _
 * |_   _|__   __|       | |                    | |
 *   | |    | |_ __   ___| |___      _____  _ __| | __  ___ ____
 *   | |    | | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ / / __|_  /
 *  _| |_   | | | | |  __/ |_ \ V  V / (_) | |  |   < | (__ / /
 * |_____|  |_|_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_(_)___/___|
 *
 *                      ___ ___ ___
 *                     | . |  _| . |  LICENCE
 *                     |  _|_| |___|
 *                     |_|
 *
 *    REKVALIFIKAČNÍ KURZY  <>  PROGRAMOVÁNÍ  <>  IT KARIÉRA
 *
 * Tento zdrojový kód je součástí profesionálních IT kurzů na
 * WWW.ITNETWORK.CZ
 *
 * Kód spadá pod licenci PRO obsahu a vznikl díky podpoře
 * našich členů. Je určen pouze pro osobní užití a nesmí být šířen.
 * Více informací na http://www.itnetwork.cz/licence
 */

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Invoices.Data.Models;

public class Person
{   /// <summary>
    /// unique id reference generated by db 
    /// </summary>
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public ulong PersonId { get; set; }
    /// <summary>
    /// name of person/company (required)
    /// </summary>
    [Required]
    public string Name { get; set; } = "";
	/// <summary>
	/// Person/Company Identification Number eg ICO (required)
	/// </summary>
	[Required]
    public string IdentificationNumber { get; set; } = "";
	/// <summary>
	/// Tax Identification Number, eg DIC (required)
	/// </summary>
	[Required]
    public string TaxNumber { get; set; } = "";
	/// <summary>
	/// Person's/Company's Account Number (required)
	/// </summary>
	[Required]
    public string AccountNumber { get; set; } = "";
	/// <summary>
	/// Bank Code (required)
	/// </summary>
	[Required]
    public string BankCode { get; set; } = "";
	/// <summary>
	/// IBAN for international banking (required)
	/// </summary>
	[Required]
    public string Iban { get; set; } = "";
	/// <summary>
	/// Person's/Company's telephone number (required)
	/// </summary>
	[Required]
    public string Telephone { get; set; } = "";
	/// <summary>
	/// Person's/Company email adrs (required)
	/// </summary>
	[Required]
    public string Mail { get; set; } = "";
	/// <summary>
	/// Person's/Company adrs street (required)
	/// </summary>
	[Required]
    public string Street { get; set; } = "";
	/// <summary>
	/// Person's/Company adrs ZIP (required)
	/// </summary>
	[Required]
    public string Zip { get; set; } = "";
	/// <summary>
	/// Person's/Company adrs City (required)
	/// </summary>
	[Required]
    public string City { get; set; } = "";
	/// <summary>
	/// Person's/Company's note (required)
	/// </summary>
	[Required]
    public string Note { get; set; } = "";
	// Czech republic / Slovakia
	[Required]
    public Country Country { get; set; }
	// hidden = false --> person is active; when person is 'deleted' it is only hidden and still in db
	[Required]
	public bool Hidden { get; set; } = false;

	/// <summary>
	/// for list of invoices, by the person
	/// </summary>
	public virtual List<Invoice> InvoicesPerPerson { get; set; } = new List<Invoice>(); 
    /// <summary>
    /// for list of invoices where person is seller
    /// </summary>
	public virtual List<Invoice> InvoicesAsSeller { get; set; } = new List<Invoice>(); 
	/// <summary>
	/// for list of invoices where person is buyer
	/// </summary>
	public virtual List<Invoice> InvoicesAsBuyer { get; set; } = new List<Invoice>();  
}